In [1]:
print("Fiverr Review Analyzer")
print("Python is working!")

Fiverr Review Analyzer
Python is working!

In [2]:
import pandas as pd
import numpy as ny

file_path="../data/raw/fiverr_reviews.csv"

df = pd.read_csv(file_path)

print("rows:", df.shape[0])
print("columns:",df.shape[1])

df.head()

rows: 107
columns: 15

,#,DESIGNATION,COUNTRY,STARS,DURATION,AGE,REVIEW,GIG,SCREENSHOTS,Unnamed: 9,Country,Count,Count.1,Gig,Count.2
0,1.0,Director,United Kingdom,5.0,3 days,2 months ago,I’ve worked with this developer on numerous pr...,API & Integrations,001_sptravel2024_United_Kingdom_5-Stars.jpg,NaN,United Kingdom,36.0,19.0,API & Integrations,48.0
1,2.0,Director and Business Growth Coordinator,Australia,5.0,2 weeks,2 months ago,"ICommuneTech was great to work with, they brok...",NaN,002_tyler_bizgrow_Australia_5-Stars.jpg,NaN,United States,18.0,9.0,NaN,30.0
2,3.0,Director,Jamaica,5.0,2 days,2 weeks ago,"He is very competent in his work,very polite,u...",API & Integrations,003_alchidanirafat_Jamaica_5-Stars.jpg,NaN,India,9.0,3.0,Backup & Migration,15.0
3,4.0,Founder,Australia,5.0,1 day,3 weeks ago,Very polite and friendly,API & Integrations,004_ruby_wagwatch_Australia_5-Stars.jpg,NaN,Australia,4.0,3.0,Full Stack Web Applications,5.0
4,5.0,Agency Owner,United States,5.0,8 days,1 month ago,Way to work with,NaN,005_andrewwagley_United_States_5-Stars.jpg,NaN,Saudi Arabia,3.0,2.0,Browser Extensions,2.0

In [3]:
df.columns.tolist()

['#',
 'DESIGNATION',
 'COUNTRY',
 'STARS',
 'DURATION',
 'AGE',
 'REVIEW',
 'GIG',
 'SCREENSHOTS',
 'Unnamed: 9',
 'Country',
 'Count',
 'Count.1',
 'Gig',
 'Count.2']

In [4]:
review_columns = [
    "DESIGNATION",
    "COUNTRY",
    "STARS",
    "DURATION",
    "AGE",
    "REVIEW",
    "GIG",
    "SCREENSHOTS"
]
reviews = df[review_columns].copy()
reviews.head()

,DESIGNATION,COUNTRY,STARS,DURATION,AGE,REVIEW,GIG,SCREENSHOTS
0,Director,United Kingdom,5.0,3 days,2 months ago,I’ve worked with this developer on numerous pr...,API & Integrations,001_sptravel2024_United_Kingdom_5-Stars.jpg
1,Director and Business Growth Coordinator,Australia,5.0,2 weeks,2 months ago,"ICommuneTech was great to work with, they brok...",NaN,002_tyler_bizgrow_Australia_5-Stars.jpg
2,Director,Jamaica,5.0,2 days,2 weeks ago,"He is very competent in his work,very polite,u...",API & Integrations,003_alchidanirafat_Jamaica_5-Stars.jpg
3,Founder,Australia,5.0,1 day,3 weeks ago,Very polite and friendly,API & Integrations,004_ruby_wagwatch_Australia_5-Stars.jpg
4,Agency Owner,United States,5.0,8 days,1 month ago,Way to work with,NaN,005_andrewwagley_United_States_5-Stars.jpg

In [5]:
reviews = reviews.rename(columns={
    "DESIGNATION": "designation",
    "COUNTRY": "country",
    "STARS": "rating",
    "DURATION": "duration",
    "AGE": "review_age",
    "REVIEW": "review_text",
    "GIG": "gig",
    "SCREENSHOTS": "screenshot"
})
reviews.head()

,designation,country,rating,duration,review_age,review_text,gig,screenshot
0,Director,United Kingdom,5.0,3 days,2 months ago,I’ve worked with this developer on numerous pr...,API & Integrations,001_sptravel2024_United_Kingdom_5-Stars.jpg
1,Director and Business Growth Coordinator,Australia,5.0,2 weeks,2 months ago,"ICommuneTech was great to work with, they brok...",NaN,002_tyler_bizgrow_Australia_5-Stars.jpg
2,Director,Jamaica,5.0,2 days,2 weeks ago,"He is very competent in his work,very polite,u...",API & Integrations,003_alchidanirafat_Jamaica_5-Stars.jpg
3,Founder,Australia,5.0,1 day,3 weeks ago,Very polite and friendly,API & Integrations,004_ruby_wagwatch_Australia_5-Stars.jpg
4,Agency Owner,United States,5.0,8 days,1 month ago,Way to work with,NaN,005_andrewwagley_United_States_5-Stars.jpg

In [6]:
reviews.isnull().sum()

designation    67
country         4
rating          4
duration       57
review_age      4
review_text     4
gig            34
screenshot      4
dtype: int64

In [7]:
reviews.duplicated(subset=["review_text"]).sum()

np.int64(8)

In [8]:
reviews = reviews.drop_duplicates(
    subset=["review_text"]
).reset_index(drop=True)

In [9]:
print("Reviews after removing duplicates:", len(reviews))

Reviews after removing duplicates: 99

In [10]:
reviews["review_text"] = reviews["review_text"].fillna("").astype(str)

reviews["review_text_clean"] = (
    reviews["review_text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [11]:
reviews[["review_text", "review_text_clean"]].head()

,review_text,review_text_clean
0,I’ve worked with this developer on numerous pr...,I’ve worked with this developer on numerous pr...
1,"ICommuneTech was great to work with, they brok...","ICommuneTech was great to work with, they brok..."
2,"He is very competent in his work,very polite,u...","He is very competent in his work,very polite,u..."
3,Very polite and friendly,Very polite and friendly
4,Way to work with,Way to work with

In [12]:
reviews["rating"] = pd.to_numeric(
    reviews["rating"],
    errors="coerce"
)

In [13]:
reviews["rating"].value_counts().sort_index()

rating
1.0     2
3.0     1
3.3     1
4.0     1
4.3     1
5.0    92
Name: count, dtype: int64

In [14]:
print("Total reviews:", len(reviews))

Total reviews: 99

In [16]:
print(
    "Average rating:",
    round(reviews["rating"].mean(), 2)
)

Average rating: 4.86

In [17]:
print(
    "Number of gigs:",
    reviews["gig"].nunique()
)

Number of gigs: 6

In [18]:
print(
    "Countries:",
    reviews["country"].nunique()
)

Countries: 26

In [19]:
gig_counts = (
    reviews["gig"]
    .value_counts()
    .reset_index()
)

gig_counts.columns = ["gig", "review_count"]

gig_counts

                           gig  review_count
0           API & Integrations            46
1           Backup & Migration            15
2  Full Stack Web Applications             5
3           Browser Extensions             2
4       AI Websites & Software             2
5                    WordPress             1

In [20]:
gig_rating = (
    reviews
    .groupby("gig")
    .agg(
        review_count=("rating", "count"),
        average_rating=("rating", "mean")
    )
    .sort_values(
        "average_rating",
        ascending=False
    )
)

gig_rating

                             review_count  average_rating
gig
Browser Extensions                      2        5.000000
Backup & Migration                     15        5.000000
Full Stack Web Applications             5        5.000000
API & Integrations                     46        4.913043
AI Websites & Software                  2        4.500000
WordPress                               1        3.000000

In [21]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

In [22]:
def get_sentiment(text):
    score = analyzer.polarity_scores(str(text))["compound"]

    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

In [23]:
reviews["sentiment"] = reviews["review_text_clean"].apply(
    get_sentiment
)

In [24]:
reviews[
    ["gig", "rating", "review_text", "sentiment"]
].head(10)

,gig,rating,review_text,sentiment
0,API & Integrations,5.0,I’ve worked with this developer on numerous pr...,Positive
1,NaN,5.0,"ICommuneTech was great to work with, they brok...",Positive
2,API & Integrations,5.0,"He is very competent in his work,very polite,u...",Positive
3,API & Integrations,5.0,Very polite and friendly,Positive
4,NaN,5.0,Way to work with,Neutral
5,Browser Extensions,5.0,"Excellent job done ,thanks for your quick resp...",Positive
6,NaN,4.3,"Very professional, I would work with him again",Neutral
7,API & Integrations,5.0,"Highly experienced team, who are very helpful ...",Positive
8,API & Integrations,5.0,It was pleasure working with you. Highly recom...,Positive
9,API & Integrations,5.0,Amazing to work with! Highly recommend!,Positive

In [25]:
sentiment_counts = reviews["sentiment"].value_counts()

sentiment_counts

sentiment
Positive    90
Neutral      7
Negative     2
Name: count, dtype: int64

In [26]:
sentiment_percentage = (
    reviews["sentiment"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

sentiment_percentage

sentiment
Positive    90.91
Neutral      7.07
Negative     2.02
Name: proportion, dtype: float64

In [27]:
gig_sentiment = pd.crosstab(
    reviews["gig"],
    reviews["sentiment"],
    normalize="index"
).mul(100).round(2)

gig_sentiment

sentiment                    Negative  Neutral  Positive
gig
AI Websites & Software           0.00     0.00    100.00
API & Integrations               2.17     4.35     93.48
Backup & Migration               0.00     0.00    100.00
Browser Extensions               0.00     0.00    100.00
Full Stack Web Applications      0.00    20.00     80.00
WordPress                        0.00   100.00      0.00

In [28]:
reviews.shape

(99, 10)

In [29]:
reviews["gig"].value_counts()

gig
API & Integrations             46
Backup & Migration             15
Full Stack Web Applications     5
Browser Extensions              2
AI Websites & Software          2
WordPress                       1
Name: count, dtype: int64

In [30]:
reviews["sentiment"].value_counts()

sentiment
Positive    90
Neutral      7
Negative     2
Name: count, dtype: int64

In [31]:
gig_sentiment = pd.crosstab(
    reviews["gig"],
    reviews["sentiment"]
)

gig_sentiment

sentiment                    Negative  Neutral  Positive
gig
AI Websites & Software              0        0         2
API & Integrations                  1        2        43
Backup & Migration                  0        0        15
Browser Extensions                  0        0         2
Full Stack Web Applications         0        1         4
WordPress                           0        1         0

In [32]:
gig_sentiment_pct = pd.crosstab(
    reviews["gig"],
    reviews["sentiment"],
    normalize="index"
).mul(100).round(2)

gig_sentiment_pct

sentiment                    Negative  Neutral  Positive
gig
AI Websites & Software           0.00     0.00    100.00
API & Integrations               2.17     4.35     93.48
Backup & Migration               0.00     0.00    100.00
Browser Extensions               0.00     0.00    100.00
Full Stack Web Applications      0.00    20.00     80.00
WordPress                        0.00   100.00      0.00

In [33]:
gig_performance = (
    reviews
    .groupby("gig")
    .agg(
        review_count=("review_text", "count"),
        average_rating=("rating", "mean")
    )
)

gig_performance["average_rating"] = (
    gig_performance["average_rating"].round(2)
)

gig_performance

                             review_count  average_rating
gig
AI Websites & Software                  2            4.50
API & Integrations                     46            4.91
Backup & Migration                     15            5.00
Browser Extensions                      2            5.00
Full Stack Web Applications             5            5.00
WordPress                               1            3.00

In [34]:
gig_performance = gig_performance.join(
    gig_sentiment_pct,
    how="left"
)

gig_performance

,review_count,average_rating,Negative,Neutral,Positive
gig,,,,,
AI Websites & Software,2,4.50,0.00,0.00,100.00
API & Integrations,46,4.91,2.17,4.35,93.48
Backup & Migration,15,5.00,0.00,0.00,100.00
Browser Extensions,2,5.00,0.00,0.00,100.00
Full Stack Web Applications,5,5.00,0.00,20.00,80.00
WordPress,1,3.00,0.00,100.00,0.00

In [35]:
reviews[reviews["gig"].isna()][
    ["rating", "review_text"]
].head(10)

    rating                                        review_text
1      5.0  ICommuneTech was great to work with, they brok...
4      5.0                                   Way to work with
6      4.3     Very professional, I would work with him again
14     NaN
15     5.0  Phase 1 of many to come. Very happy with their...
18     5.0                   excellent job! highly recommnend
27     5.0            My go to company, great work! Thank you
32     5.0  Amazing work! Highly recommend and have used f...
42     5.0  Icommunetech delivered great work. I was very ...
48     5.0  The best ever in fiverr I realy recommended hi...

In [36]:
pd.crosstab(reviews["gig"], reviews["sentiment"])

sentiment                    Negative  Neutral  Positive
gig
AI Websites & Software              0        0         2
API & Integrations                  1        2        43
Backup & Migration                  0        0        15
Browser Extensions                  0        0         2
Full Stack Web Applications         0        1         4
WordPress                           0        1         0

In [37]:
gig_performance

,review_count,average_rating,Negative,Neutral,Positive
gig,,,,,
AI Websites & Software,2,4.50,0.00,0.00,100.00
API & Integrations,46,4.91,2.17,4.35,93.48
Backup & Migration,15,5.00,0.00,0.00,100.00
Browser Extensions,2,5.00,0.00,0.00,100.00
Full Stack Web Applications,5,5.00,0.00,20.00,80.00
WordPress,1,3.00,0.00,100.00,0.00

In [38]:
reviews[reviews["gig"].isna()][["rating", "review_text"]].head(10)

    rating                                        review_text
1      5.0  ICommuneTech was great to work with, they brok...
4      5.0                                   Way to work with
6      4.3     Very professional, I would work with him again
14     NaN
15     5.0  Phase 1 of many to come. Very happy with their...
18     5.0                   excellent job! highly recommnend
27     5.0            My go to company, great work! Thank you
32     5.0  Amazing work! Highly recommend and have used f...
42     5.0  Icommunetech delivered great work. I was very ...
48     5.0  The best ever in fiverr I realy recommended hi...

In [39]:
import os
from dotenv import load_dotenv

load_dotenv()

ollama_api_key = os.getenv("OLLAMA_API_KEY")

if not ollama_api_key:
    raise ValueError("OLLAMA_API_KEY not found")

print("Ollama API key loaded successfully")

Ollama API key loaded successfully

In [40]:
from ollama import Client

client = Client(
    host="https://ollama.com",
    headers={
        "Authorization": f"Bearer {ollama_api_key}"
    }
)

In [43]:
response = client.chat(
    model="gpt-oss:20b-cloud",
    messages=[
        {
            "role": "user",
            "content": "Explain sentiment analysis in one sentence."
        }
    ]
)

print(response["message"]["content"])

Sentiment analysis is the automated process of identifying and classifying the emotional tone—positive, negative, or neutral—expressed in a piece of text using natural‑language processing techniques.

In [44]:
import re
import pandas as pd

def clean_review_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Replace line breaks/tabs with spaces
    text = re.sub(r"[\r\n\t]+", " ", text)

    # Remove excessive whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove leading/trailing spaces
    text = text.strip()

    return text


reviews["review_text_llm"] = reviews["review_text"].apply(clean_review_text)

In [45]:
reviews[["review_text", "review_text_llm"]].head()

,review_text,review_text_llm
0,I’ve worked with this developer on numerous pr...,i’ve worked with this developer on numerous pr...
1,"ICommuneTech was great to work with, they brok...","icommunetech was great to work with, they brok..."
2,"He is very competent in his work,very polite,u...","he is very competent in his work,very polite,u..."
3,Very polite and friendly,very polite and friendly
4,Way to work with,way to work with

In [46]:
print("Total reviews:", len(reviews))
print("Empty reviews:", (reviews["review_text_llm"] == "").sum())

Total reviews: 99
Empty reviews: 1

In [47]:
reviews["review_length"] = reviews["review_text_llm"].str.len()

reviews["review_length"].describe()

count     99.000000
mean      82.636364
std       94.531115
min        0.000000
25%       29.000000
50%       47.000000
75%       97.500000
max      618.000000
Name: review_length, dtype: float64

In [49]:
def clean_review_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Replace line breaks/tabs with spaces
    text = re.sub(r"[\r\n\t]+", " ", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


reviews["review_text_llm"] = reviews["review_text"].apply(clean_review_text)

In [50]:
SYSTEM_PROMPT = """
You are an expert AI analyst specializing in Fiverr client feedback and NLP.

Analyze the provided Fiverr client review objectively.

Return a structured analysis containing:

- sentiment:
  One of: Positive, Neutral, Negative, Mixed

- confidence:
  A number between 0 and 1 representing confidence in the sentiment.

- satisfaction:
  A number between 0 and 1 representing the client's apparent satisfaction.

- strengths:
  Specific things the client liked or praised.

- improvement_areas:
  Specific problems, concerns, weaknesses, or areas that could be improved.

- topics:
  Select relevant topics from:
  Communication
  Technical Quality
  Delivery
  Requirements
  Reliability
  Professionalism
  Problem Solving
  Revisions
  Pricing
  Other

- explanation:
  A short explanation supporting the sentiment classification.

- recommendation:
  A practical recommendation based only on the review.

IMPORTANT:
- Analyze only the review provided.
- Do not invent problems.
- Do not assume that every review has an improvement area.
- If there is no improvement area, return an empty list.
- Be specific and evidence-based.
"""

In [51]:
test_review = reviews.iloc[0]["review_text_llm"]

print(test_review)

i’ve worked with this developer on numerous projects and continue to come back because of the quality of work delivered. communication is excellent, deadlines are met, and even complex requirements are handled professionally. they have been instrumental in helping develop and improve my travel platform, consistently providing solutions, fixing issues quickly, and suggesting improvements along the way. highly skilled, reliable, and a pleasure to work with. i would not hesitate to recommend them and look forward to continuing our collaboration on future projects. thank you again for your hard work and dedication.

In [52]:
response = client.chat(
    model="gpt-oss:20b-cloud",
    messages=[
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": f"""
Analyze this Fiverr client review:

{test_review}
"""
        }
    ]
)

llm_result = response["message"]["content"]

print(llm_result)

**Sentiment:** Positive
**Confidence:** 0.95
**Satisfaction:** 0.98

**Strengths**
- Consistently high‑quality work on multiple projects.
- Excellent communication (clear, timely updates).
- On‑time delivery – deadlines are met without issue.
- Handles complex requirements professionally.
- Provides quick issue resolution and proactive solutions.
- Suggests platform improvements, indicating a proactive partnership.
- Demonstrates strong technical skill, reliability, and professionalism.

**Improvement Areas**
[]  *(none identified)*

**Topics**
- Communication
- Technical Quality
- Delivery
- Requirements
- Reliability
- Professionalism
- Problem Solving

**Explanation**
The review is unequivocally enthusiastic, praising the developer on every key success metric and expressing a desire to continue the partnership. There are no contrary statements or complaints, leading to a high confidence positive assessment.

**Recommendation**
Maintain the current level of proactive communication and rapid issue‑resolution practices. Continue to leverage the developer’s expertise on future travels‑platform enhancements, and consider formally acknowledging their contributions to reinforce the long‑term relationship.

In [53]:
reviews = reviews.reset_index(drop=True)

reviews["review_id"] = reviews.index + 1

reviews[["review_id", "review_text_llm"]].head()

   review_id                                    review_text_llm
0          1  i’ve worked with this developer on numerous pr...
1          2  icommunetech was great to work with, they brok...
2          3  he is very competent in his work,very polite,u...
3          4                           very polite and friendly
4          5                                   way to work with

In [54]:
from pydantic import BaseModel, Field
from typing import List, Literal


class ReviewAnalysis(BaseModel):
    sentiment: Literal[
        "Positive",
        "Neutral",
        "Negative",
        "Mixed"
    ]

    confidence: float = Field(
        ge=0,
        le=1
    )

    satisfaction: float = Field(
        ge=0,
        le=1
    )

    strengths: List[str]

    improvement_areas: List[str]

    topics: List[str]

    explanation: str

    recommendation: str

In [55]:
SYSTEM_PROMPT = """
You are an expert AI analyst specializing in Fiverr client feedback and NLP.

Analyze the provided Fiverr client review.

Return ONLY valid JSON matching the requested schema.

Analyze:

1. sentiment
   - Positive
   - Neutral
   - Negative
   - Mixed

2. confidence
   Number between 0 and 1.

3. satisfaction
   Number between 0 and 1.

4. strengths
   Specific things the client liked or praised.

5. improvement_areas
   Specific problems, concerns, weaknesses, or areas that could be improved.

6. topics
   Select only relevant topics from:
   - Communication
   - Technical Quality
   - Delivery
   - Requirements
   - Reliability
   - Professionalism
   - Problem Solving
   - Revisions
   - Pricing
   - Other

7. explanation
   Brief explanation of the analysis.

8. recommendation
   Practical recommendation based only on the review.

IMPORTANT:
- Analyze only the review.
- Do not invent problems.
- Do not assume a problem exists.
- If no improvement area is mentioned or reasonably implied, return [].
- Do not use the Fiverr star rating to determine sentiment.
- Keep the analysis concise and evidence-based.
"""

In [56]:
test_review = reviews.iloc[0]["review_text_llm"]

response = client.chat(
    model="gpt-oss:20b-cloud",
    messages=[
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": test_review
        }
    ],
    format=ReviewAnalysis.model_json_schema()
)

print(response["message"]["content"])

```json
{
  "sentiment": "Positive",
  "confidence": 0.95,
  "satisfaction": 0.98,
  "strengths": [
    "High quality of work delivered",
    "Excellent communication",
    "On-time delivery and meeting deadlines",
    "Professional handling of complex requirements",
    "Fast issue fixing and problem solving",
    "Proactive suggestions for improvement",
    "Reliability and skillfulness"
  ],
  "improvement_areas": [],
  "topics": [
    "Communication",
    "Technical Quality",
    "Delivery",
    "Requirements",
    "Reliability",
    "Professionalism",
    "Problem Solving"
  ],
  "explanation": "The review contains multiple explicit praises for quality, communication, reliability, and problem‑solving speed. No negative remarks or concerns are mentioned, indicating a wholly positive experience.",
  "recommendation": "Continue to build on strong communication and reliability, maintain clear requirement briefs for upcoming projects, and leverage their proactive improvement suggestions to further enhance the travel platform."
}
```

In [60]:
import json
import re

def clean_llm_json(text):
    """
    Clean JSON returned by an LLM.
    Handles ```json ... ``` and plain JSON.
    """

    text = text.strip()

    # Remove markdown code fence
    text = re.sub(r"^```json\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    return text.strip()

In [61]:
cleaned_json = clean_llm_json(
    response["message"]["content"]
)

print(cleaned_json)

{
  "sentiment": "Positive",
  "confidence": 0.95,
  "satisfaction": 0.98,
  "strengths": [
    "High quality of work delivered",
    "Excellent communication",
    "On-time delivery and meeting deadlines",
    "Professional handling of complex requirements",
    "Fast issue fixing and problem solving",
    "Proactive suggestions for improvement",
    "Reliability and skillfulness"
  ],
  "improvement_areas": [],
  "topics": [
    "Communication",
    "Technical Quality",
    "Delivery",
    "Requirements",
    "Reliability",
    "Professionalism",
    "Problem Solving"
  ],
  "explanation": "The review contains multiple explicit praises for quality, communication, reliability, and problem‑solving speed. No negative remarks or concerns are mentioned, indicating a wholly positive experience.",
  "recommendation": "Continue to build on strong communication and reliability, maintain clear requirement briefs for upcoming projects, and leverage their proactive improvement suggestions to further enhance the travel platform."
}

In [62]:
analysis = ReviewAnalysis.model_validate_json(
    cleaned_json
)

print(analysis)

sentiment='Positive' confidence=0.95 satisfaction=0.98 strengths=['High quality of work delivered', 'Excellent communication', 'On-time delivery and meeting deadlines', 'Professional handling of complex requirements', 'Fast issue fixing and problem solving', 'Proactive suggestions for improvement', 'Reliability and skillfulness'] improvement_areas=[] topics=['Communication', 'Technical Quality', 'Delivery', 'Requirements', 'Reliability', 'Professionalism', 'Problem Solving'] explanation='The review contains multiple explicit praises for quality, communication, reliability, and problem‑solving speed. No negative remarks or concerns are mentioned, indicating a wholly positive experience.' recommendation='Continue to build on strong communication and reliability, maintain clear requirement briefs for upcoming projects, and leverage their proactive improvement suggestions to further enhance the travel platform.'

In [63]:
print("Sentiment:", analysis.sentiment)
print("Confidence:", analysis.confidence)
print("Satisfaction:", analysis.satisfaction)
print("Strengths:", analysis.strengths)
print("Improvement Areas:", analysis.improvement_areas)
print("Topics:", analysis.topics)
print("Explanation:", analysis.explanation)
print("Recommendation:", analysis.recommendation)

Sentiment: Positive
Confidence: 0.95
Satisfaction: 0.98
Strengths: ['High quality of work delivered', 'Excellent communication', 'On-time delivery and meeting deadlines', 'Professional handling of complex requirements', 'Fast issue fixing and problem solving', 'Proactive suggestions for improvement', 'Reliability and skillfulness']
Improvement Areas: []
Topics: ['Communication', 'Technical Quality', 'Delivery', 'Requirements', 'Reliability', 'Professionalism', 'Problem Solving']
Explanation: The review contains multiple explicit praises for quality, communication, reliability, and problem‑solving speed. No negative remarks or concerns are mentioned, indicating a wholly positive experience.
Recommendation: Continue to build on strong communication and reliability, maintain clear requirement briefs for upcoming projects, and leverage their proactive improvement suggestions to further enhance the travel platform.

In [64]:
def analyze_review(review_text):

    response = client.chat(
        model="gpt-oss:20b-cloud",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": review_text
            }
        ],
        format=ReviewAnalysis.model_json_schema()
    )

    raw_result = response["message"]["content"]

    cleaned_result = clean_llm_json(raw_result)

    analysis = ReviewAnalysis.model_validate_json(
        cleaned_result
    )

    return analysis

In [65]:
result = analyze_review(
    reviews.iloc[0]["review_text_llm"]
)

print(result)

sentiment='Positive' confidence=0.95 satisfaction=0.95 strengths=['High quality of work delivered', 'Excellent communication', 'Consistent deadline adherence', 'Professional handling of complex requirements', 'Effective development and improvement of travel platform', 'Fast issue resolution', 'Proactive suggestions for improvements', 'High skill level', 'Reliability', 'Pleasant working relationship', 'Willingness to recommend'] improvement_areas=[] topics=['Communication', 'Technical Quality', 'Delivery', 'Requirements', 'Reliability', 'Professionalism', 'Problem Solving'] explanation='The review is entirely positive, highlighting multiple strengths such as communication, quality, reliability, problem solving, and professionalism. No issues or areas for improvement are mentioned. The sentiment is strongly positive with high confidence.' recommendation='Sustain the strong collaboration by continuing clear communication, meeting deadlines, and proactively offering improvement ideas; consider scheduling regular review checkpoints for future projects.'

In [66]:
for i in range(3):

    result = analyze_review(
        reviews.iloc[i]["review_text_llm"]
    )

    print("\n-----------------------------")
    print("Review:", i + 1)
    print("Sentiment:", result.sentiment)
    print("Confidence:", result.confidence)
    print("Satisfaction:", result.satisfaction)
    print("Strengths:", result.strengths)
    print("Improvement:", result.improvement_areas)
    print("Topics:", result.topics)

-----------------------------
Review: 1
Sentiment: Positive
Confidence: 0.94
Satisfaction: 0.94
Strengths: ['excellent communication', 'meeting deadlines', 'high quality of work', 'handling complex requirements professionally', 'technical skill and expertise', 'reliable delivery', 'quick issue resolution', 'proactive suggestions for improvement', 'instrumental role in platform development']
Improvement: []
Topics: ['Communication', 'Delivery', 'Technical Quality', 'Reliability', 'Professionalism', 'Requirements', 'Problem Solving']

-----------------------------
Review: 2
Sentiment: Positive
Confidence: 0.9
Satisfaction: 0.9
Strengths: ['Great working experience', 'Clear milestone breakdown', 'Ensured each element was understood and completed perfectly']
Improvement: []
Topics: ['Communication']

-----------------------------
Review: 3
Sentiment: Positive
Confidence: 0.95
Satisfaction: 0.95
Strengths: ['competence', 'politeness', 'understanding', 'efficiency', 'exceeded expectations']
Improvement: []
Topics: ['Communication', 'Technical Quality', 'Delivery']

In [67]:
import os
import json
import time
import pandas as pd
from datetime import datetime

OUTPUT_FILE = "outputs/llm_review_analysis.csv"

# Make sure output directory exists
os.makedirs("outputs", exist_ok=True)


def analyze_review(review_text):
    """
    Send one review to Ollama Cloud and return structured analysis.
    """

    response = client.chat(
        model="gpt-oss:20b-cloud",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": review_text
            }
        ],
        format=ReviewAnalysis.model_json_schema()
    )

    raw_result = response["message"]["content"]

    cleaned_result = clean_llm_json(raw_result)

    analysis = ReviewAnalysis.model_validate_json(
        cleaned_result
    )

    return analysis

In [68]:
def save_analysis_result(review_id, analysis, status="success", error=None):

    result = {
        "review_id": review_id,
        "llm_sentiment": analysis.sentiment if analysis else None,
        "llm_confidence": analysis.confidence if analysis else None,
        "satisfaction": analysis.satisfaction if analysis else None,
        "strengths": json.dumps(
            analysis.strengths,
            ensure_ascii=False
        ) if analysis else None,
        "improvement_areas": json.dumps(
            analysis.improvement_areas,
            ensure_ascii=False
        ) if analysis else None,
        "topics": json.dumps(
            analysis.topics,
            ensure_ascii=False
        ) if analysis else None,
        "explanation": analysis.explanation if analysis else None,
        "recommendation": analysis.recommendation if analysis else None,
        "status": status,
        "error": error,
        "processed_at": datetime.now().isoformat()
    }

    result_df = pd.DataFrame([result])

    # Append to CSV
    if os.path.exists(OUTPUT_FILE):
        result_df.to_csv(
            OUTPUT_FILE,
            mode="a",
            header=False,
            index=False,
            encoding="utf-8-sig"
        )
    else:
        result_df.to_csv(
            OUTPUT_FILE,
            mode="w",
            header=True,
            index=False,
            encoding="utf-8-sig"
        )

In [69]:
def save_analysis_result(review_id, analysis, status="success", error=None):

    result = {
        "review_id": review_id,
        "llm_sentiment": analysis.sentiment if analysis else None,
        "llm_confidence": analysis.confidence if analysis else None,
        "satisfaction": analysis.satisfaction if analysis else None,
        "strengths": json.dumps(
            analysis.strengths,
            ensure_ascii=False
        ) if analysis else None,
        "improvement_areas": json.dumps(
            analysis.improvement_areas,
            ensure_ascii=False
        ) if analysis else None,
        "topics": json.dumps(
            analysis.topics,
            ensure_ascii=False
        ) if analysis else None,
        "explanation": analysis.explanation if analysis else None,
        "recommendation": analysis.recommendation if analysis else None,
        "status": status,
        "error": error,
        "processed_at": datetime.now().isoformat()
    }

    result_df = pd.DataFrame([result])

    # Append to CSV
    if os.path.exists(OUTPUT_FILE):
        result_df.to_csv(
            OUTPUT_FILE,
            mode="a",
            header=False,
            index=False,
            encoding="utf-8-sig"
        )
    else:
        result_df.to_csv(
            OUTPUT_FILE,
            mode="w",
            header=True,
            index=False,
            encoding="utf-8-sig"
        )

In [70]:
reviews["review_id"].head()

0    1
1    2
2    3
3    4
4    5
Name: review_id, dtype: int64

In [72]:
def process_all_reviews(reviews):

    # Check already processed reviews
    if os.path.exists(OUTPUT_FILE):

        existing = pd.read_csv(
            OUTPUT_FILE
        )

        processed_ids = set(
            existing.loc[
                existing["status"] == "success",
                "review_id"
            ]
        )

        print(
            f"Already processed: {len(processed_ids)} reviews"
        )

    else:

        processed_ids = set()

        print("Starting new analysis...")

    total = len(reviews)

    for index, row in reviews.iterrows():

        review_id = int(row["review_id"])

        # Skip already completed reviews
        if review_id in processed_ids:
            continue

        review_text = row["review_text_llm"]

        print(
            f"Processing {review_id}/{total}..."
        )

        try:

            # Skip empty reviews
            if not review_text or not review_text.strip():

                print(
                    f"Review {review_id}: empty text"
                )

                save_analysis_result(
                    review_id,
                    None,
                    status="skipped",
                    error="Empty review text"
                )

                continue

            # Analyze with Ollama
            analysis = analyze_review(
                review_text
            )

            # Save immediately
            save_analysis_result(
                review_id,
                analysis,
                status="success"
            )

            print(
                f"✓ Review {review_id}: "
                f"{analysis.sentiment}"
            )

        except Exception as e:

            error_message = str(e)

            print(
                f"✗ Review {review_id} failed: "
                f"{error_message}"
            )

            save_analysis_result(
                review_id,
                None,
                status="error",
                error=error_message
            )

        # Small delay between API calls
        time.sleep(0.5)

    print("\nAnalysis completed.")

In [73]:
reviews["review_id"].head()

0    1
1    2
2    3
3    4
4    5
Name: review_id, dtype: int64

In [74]:
process_all_reviews(reviews)

Starting new analysis...
Processing 1/99...
✓ Review 1: Positive
Processing 2/99...
✓ Review 2: Positive
Processing 3/99...
✓ Review 3: Positive
Processing 4/99...
✓ Review 4: Positive
Processing 5/99...
✓ Review 5: Neutral
Processing 6/99...
✓ Review 6: Positive
Processing 7/99...
✓ Review 7: Positive
Processing 8/99...
✓ Review 8: Positive
Processing 9/99...
✓ Review 9: Positive
Processing 10/99...
✓ Review 10: Positive
Processing 11/99...
✓ Review 11: Positive
Processing 12/99...
✓ Review 12: Positive
Processing 13/99...
✓ Review 13: Positive
Processing 14/99...
✓ Review 14: Positive
Processing 15/99...
Review 15: empty text
Processing 16/99...
✓ Review 16: Positive
Processing 17/99...
✓ Review 17: Positive
Processing 18/99...
✓ Review 18: Positive
Processing 19/99...
✓ Review 19: Positive
Processing 20/99...
✓ Review 20: Positive
Processing 21/99...
✓ Review 21: Positive
Processing 22/99...
✓ Review 22: Positive
Processing 23/99...
✓ Review 23: Positive
Processing 24/99...
✓ Review 24: Positive
Processing 25/99...
✓ Review 25: Positive
Processing 26/99...
✓ Review 26: Positive
Processing 27/99...
✓ Review 27: Positive
Processing 28/99...
✓ Review 28: Positive
Processing 29/99...
✓ Review 29: Positive
Processing 30/99...
✓ Review 30: Positive
Processing 31/99...
✓ Review 31: Positive
Processing 32/99...
✓ Review 32: Positive
Processing 33/99...
✓ Review 33: Positive
Processing 34/99...
✓ Review 34: Positive
Processing 35/99...
✓ Review 35: Positive
Processing 36/99...
✓ Review 36: Positive
Processing 37/99...
✓ Review 37: Positive
Processing 38/99...
✓ Review 38: Positive
Processing 39/99...
✓ Review 39: Positive
Processing 40/99...
✓ Review 40: Positive
Processing 41/99...
✓ Review 41: Positive
Processing 42/99...
✓ Review 42: Positive
Processing 43/99...
✓ Review 43: Positive
Processing 44/99...
✓ Review 44: Positive
Processing 45/99...
✓ Review 45: Positive
Processing 46/99...
✓ Review 46: Positive
Processing 47/99...
✓ Review 47: Positive
Processing 48/99...
✓ Review 48: Positive
Processing 49/99...
✓ Review 49: Positive
Processing 50/99...
✓ Review 50: Positive
Processing 51/99...
✓ Review 51: Positive
Processing 52/99...
✓ Review 52: Positive
Processing 53/99...
✓ Review 53: Positive
Processing 54/99...
✓ Review 54: Positive
Processing 55/99...
✓ Review 55: Positive
Processing 56/99...
✓ Review 56: Positive
Processing 57/99...
✓ Review 57: Positive
Processing 58/99...
✓ Review 58: Positive
Processing 59/99...
✓ Review 59: Positive
Processing 60/99...
✓ Review 60: Positive
Processing 61/99...
✓ Review 61: Positive
Processing 62/99...
✓ Review 62: Positive
Processing 63/99...
✓ Review 63: Positive
Processing 64/99...
✓ Review 64: Positive
Processing 65/99...
✓ Review 65: Positive
Processing 66/99...
✓ Review 66: Positive
Processing 67/99...
✓ Review 67: Positive
Processing 68/99...
✓ Review 68: Positive
Processing 69/99...
✓ Review 69: Positive
Processing 70/99...
✓ Review 70: Positive
Processing 71/99...
✓ Review 71: Positive
Processing 72/99...
✓ Review 72: Positive
Processing 73/99...
✓ Review 73: Positive
Processing 74/99...
✓ Review 74: Positive
Processing 75/99...
✓ Review 75: Positive
Processing 76/99...
✓ Review 76: Positive
Processing 77/99...
✓ Review 77: Positive
Processing 78/99...
✓ Review 78: Positive
Processing 79/99...
✓ Review 79: Positive
Processing 80/99...
✓ Review 80: Positive
Processing 81/99...
✓ Review 81: Positive
Processing 82/99...
✓ Review 82: Positive
Processing 83/99...
✓ Review 83: Positive
Processing 84/99...
✓ Review 84: Positive
Processing 85/99...
✓ Review 85: Positive
Processing 86/99...
✓ Review 86: Positive
Processing 87/99...
✓ Review 87: Positive
Processing 88/99...
✓ Review 88: Positive
Processing 89/99...
✓ Review 89: Positive
Processing 90/99...
✓ Review 90: Positive
Processing 91/99...
✓ Review 91: Positive
Processing 92/99...
✓ Review 92: Positive
Processing 93/99...
✓ Review 93: Positive
Processing 94/99...
✓ Review 94: Positive
Processing 95/99...
✓ Review 95: Positive
Processing 96/99...
✓ Review 96: Positive
Processing 97/99...
✓ Review 97: Neutral
Processing 98/99...
✓ Review 98: Negative
Processing 99/99...
✓ Review 99: Negative

Analysis completed.

In [75]:
llm_results = pd.read_csv(
    OUTPUT_FILE
)

print(llm_results.shape)

(99, 12)

In [76]:
llm_results.head()

,review_id,llm_sentiment,llm_confidence,satisfaction,strengths,improvement_areas,topics,explanation,recommendation,status,error,processed_at
0,1,Positive,0.95,0.95,"[""high quality of work delivered"", ""excellent ...",[],"[""Communication"", ""Technical Quality"", ""Delive...",The review contains only positive remarks desc...,Maintain the established high standards and co...,success,NaN,2026-09-22T17:51:43.638647
1,2,Positive,0.95,0.95,"[""Great to work with"", ""Broke down the job int...",[],"[""Communication"", ""Delivery"", ""Requirements"", ...","The review praises the vendor’s communication,...",Continue using a milestone-based approach and ...,success,NaN,2026-09-22T17:51:59.389964
2,3,Positive,0.95,0.95,"[""competent work"", ""polite and understanding d...",[],"[""Communication"", ""Technical Quality"", ""Delive...",The client explicitly praises the seller’s com...,"Continue offering clear, efficient services wh...",success,NaN,2026-09-22T17:52:13.422814
3,4,Positive,0.90,0.85,"[""polite communication"", ""friendly tone""]",[],"[""Communication""]",The review expresses positive sentiments about...,Continue emphasizing polite and friendly commu...,success,NaN,2026-09-22T17:52:22.261833
4,5,Neutral,0.30,0.50,"[""Positive working process""]",[],"[""Communication"", ""Professionalism""]",The review is very brief and contains no expli...,"Encourage the seller to provide clearer, more ...",success,NaN,2026-09-22T17:52:35.852424

In [77]:
llm_results["status"].value_counts()

status
success    98
skipped     1
Name: count, dtype: int64

In [78]:
llm_results[
    llm_results["status"] == "error"
][
    ["review_id", "error"]
]

Empty DataFrame
Columns: [review_id, error]
Index: []

In [79]:
final_reviews = reviews.merge(
    llm_results,
    on="review_id",
    how="left"
)

In [81]:
final_reviews.shape

(99, 24)

In [82]:
final_reviews[
    [
        "review_id",
        "gig",
        "rating",
        "llm_sentiment",
        "satisfaction",
        "improvement_areas",
        "topics"
    ]
].head()

,review_id,gig,rating,llm_sentiment,satisfaction,improvement_areas,topics
0,1,API & Integrations,5.0,Positive,0.95,[],"[""Communication"", ""Technical Quality"", ""Delive..."
1,2,NaN,5.0,Positive,0.95,[],"[""Communication"", ""Delivery"", ""Requirements"", ..."
2,3,API & Integrations,5.0,Positive,0.95,[],"[""Communication"", ""Technical Quality"", ""Delive..."
3,4,API & Integrations,5.0,Positive,0.85,[],"[""Communication""]"
4,5,NaN,5.0,Neutral,0.50,[],"[""Communication"", ""Professionalism""]"

In [83]:
final_reviews["llm_sentiment"].value_counts()

llm_sentiment
Positive    94
Neutral      2
Negative     2
Name: count, dtype: int64

In [85]:
final_reviews["satisfaction"].mean()

np.float64(0.8977551020408163)

In [86]:
pd.crosstab(
    final_reviews["gig"],
    final_reviews["llm_sentiment"]
)

llm_sentiment                Negative  Neutral  Positive
gig
AI Websites & Software              0        0         2
API & Integrations                  1        0        45
Backup & Migration                  0        0        15
Browser Extensions                  0        0         2
Full Stack Web Applications         0        0         5
WordPress                           0        1         0

In [87]:
gig_ai_performance = (
    final_reviews
    .groupby("gig")
    .agg(
        review_count=("review_id", "count"),
        average_rating=("rating", "mean"),
        average_satisfaction=("satisfaction", "mean"),
        average_confidence=("llm_confidence", "mean")
    )
    .round(2)
)

gig_ai_performance

,review_count,average_rating,average_satisfaction,average_confidence
gig,,,,
AI Websites & Software,2,4.50,0.89,0.94
API & Integrations,46,4.91,0.91,0.94
Backup & Migration,15,5.00,0.93,0.94
Browser Extensions,2,5.00,0.96,0.96
Full Stack Web Applications,5,5.00,0.91,0.95
WordPress,1,3.00,0.20,0.20

In [88]:
llm_results = pd.read_csv(
    "outputs/llm_review_analysis.csv"
)

print(llm_results["status"].value_counts())

status
success    98
skipped     1
Name: count, dtype: int64

In [90]:
final_reviews = reviews.merge(
    llm_results,
    on="review_id",
    how="left"
)

print(final_reviews.shape)

(99, 24)

In [92]:
llm_results = pd.read_csv(
    "outputs/llm_review_analysis.csv"
)

print(llm_results["status"].value_counts())

status
success    98
skipped     1
Name: count, dtype: int64

In [93]:
final_reviews = reviews.merge(
    llm_results,
    on="review_id",
    how="left"
)

print("Original reviews:", len(reviews))
print("Final reviews:", len(final_reviews))

Original reviews: 99
Final reviews: 99

In [94]:
print(
    final_reviews["llm_sentiment"]
    .value_counts(dropna=False)
)

llm_sentiment
Positive    94
Neutral      2
Negative     2
NaN          1
Name: count, dtype: int64

In [95]:
sentiment_summary = (
    final_reviews["llm_sentiment"]
    .value_counts(normalize=True, dropna=True)
    .mul(100)
    .round(2)
)

print(sentiment_summary)

llm_sentiment
Positive    95.92
Neutral      2.04
Negative     2.04
Name: proportion, dtype: float64